-- =============================================================================
-- Sem migrations pendentes (verificado 2026-05-12)
-- =============================================================================
-- Última corrida: 0028_h2h_and_opponents.sql
-- O próximo lote vai voltar a popular este ficheiro quando houver SQL novo.
