-- =============================================================================
-- Sem migrations pendentes (verificado 2026-05-12)
-- =============================================================================
-- Última corrida: 0026_friends_activity.sql
-- O próximo lote vai voltar a popular este ficheiro quando houver SQL novo.
